# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
    # specify the version you desire here
    - image: circleci/php:7.1-browsers

    # Specify service dependencies here if necessary
    # CircleCI maintains a library of pre-built images
    # documented at https://circleci.com/docs/2.0/circleci-images/
    # - image: circleci/mysql:9.4

    working_directory: ~/repo

    parallelism: 4

    steps:
    - checkout
    - run:
        command: ./vendor/bin/steward install 3.8.1
        background: true
    - run: sleep 10
    - run:
        command: java -jar ./vendor/bin/selenium-server-standalone-3.8.1.jar > /dev/null 2>&1 &
        background: true
    - run: sleep 10

    # Download and cache dependencies
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "composer.json" }}
        # fallback to using the latest cache if no exact match is found
        - v1-dependencies-

    - run: composer install -n --prefer-dist

    - save_cache:
        paths:
        - ./vendor
        key: v1-dependencies-{{ checksum "composer.json" }}

    # run tests!
    - run: ./vendor/bin/steward run production chrome -vvv